spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: "optional:configserver:http://localhost:8089"
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service_db?createDatabaseIfNotExist=true
    username: root
    password: Piyumika617
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql

